server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Serve static files (JS, CSS, images)
    location /assets/ {
        try_files $uri =404;
    }

    # React routing (VERY IMPORTANT)
    location / {
        try_files $uri /index.html;
    }
}